#!/bin/bash

FILES=$(git diff --cached --name-status)

if [[ $FILES =~ .drawio ]]; then
    echo
    echo --- Auto-generating SVG files for architecture diagrams ---
    /Applications/draw.io.app/Contents/MacOS/draw.io -x social-app/architecture.drawio -f svg -s 1 social-app/architecture.svg
    git add social-app/architecture.svg
    echo
fi

exit 0
