// On-topic relevance gate (NAKO-34).
//
// Embeds the user's query with Titan and cosine-compares it against the baked
// CV/portfolio exemplar vectors (topic-vectors.json, generated by
// scripts/generate-topic-vectors.ts). A query whose best match falls below the
// threshold is treated as off-topic and hard-blocked before the agent is called.
//
// No vector DB: the exemplars are a small static array bundled with the Lambda,
// and both they and the query are L2-normalised, so "cosine similarity" is just
// a dot product. Only per-request cost is one Titan embed of the query.
//
// The baked vectors carry their source text (each { text, vector }) so the gate
// can report WHICH exemplar a query matched — handy for tuning and for spotting
// which sentence to prune.
import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime';
import { EMBED_MODEL_ID, EMBED_DIMS, BEDROCK_REGION } from './embed-config';
import topicVectors from './topic-vectors.json';

// Cosine threshold for "on-topic". Tunable at runtime via RELEVANCE_THRESHOLD
// without a code change. 0.22 is the starting point carried over from the blog
// search (blog-retriever.ts) and the home-infra gate; tune against real CV-style
// questions vs off-topic once the exemplars are baked.
const DEFAULT_THRESHOLD = 0.22;

const client = new BedrockRuntimeClient({ region: BEDROCK_REGION });

interface BakedEntry {
    text: string;
    vector: number[];
}
interface BakedVectors {
    model: string;
    dims: number;
    normalized: boolean;
    count: number;
    entries: BakedEntry[];
}
const TOPICS = topicVectors as BakedVectors;

export interface RelevanceResult {
    onTopic: boolean;
    /** Best cosine similarity against any exemplar (higher = more on-topic). */
    score: number;
    threshold: number;
    /** The exemplar the query matched most closely (for tuning/observability). */
    matched: string | null;
}

export function relevanceThreshold(): number {
    const v = Number(process.env.RELEVANCE_THRESHOLD);
    return Number.isFinite(v) ? v : DEFAULT_THRESHOLD;
}

function dot(a: number[], b: number[]): number {
    let s = 0;
    for (let i = 0; i < a.length; i++) s += a[i] * b[i];
    return s;
}

/** Best cosine of a (unit) query vector against the baked (unit) exemplars, with
 *  the matching exemplar's text. Pure. */
export function bestMatch(queryVec: number[]): { score: number; text: string | null } {
    let score = -Infinity;
    let text: string | null = null;
    for (const e of TOPICS.entries) {
        const s = dot(queryVec, e.vector);
        if (s > score) {
            score = s;
            text = e.text;
        }
    }
    return { score, text };
}

async function embedQuery(text: string): Promise<number[]> {
    const res = await client.send(
        new InvokeModelCommand({
            modelId: EMBED_MODEL_ID,
            contentType: 'application/json',
            accept: 'application/json',
            body: JSON.stringify({ inputText: text, dimensions: EMBED_DIMS, normalize: true }),
        }),
    );
    const parsed = JSON.parse(new TextDecoder().decode(res.body)) as { embedding: number[] };
    return parsed.embedding;
}

/**
 * Whether `query` is on-topic for the CV assistant. Empty/whitespace queries are
 * treated as on-topic (nothing to screen). Never returns a "blocked" verdict by
 * throwing — a Titan failure propagates to the caller, which decides whether to
 * fail open.
 */
export async function isOnTopic(query: string): Promise<RelevanceResult> {
    const threshold = relevanceThreshold();
    if (!query.trim()) return { onTopic: true, score: 1, threshold, matched: null };
    const { score, text } = bestMatch(await embedQuery(query));
    return { onTopic: score >= threshold, score, threshold, matched: text };
}
