#!/bin/bash
AWS_PROFILE=nakom.is
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
aws s3 sync --exclude ".DS_Store" $SCRIPT_DIR/../s3contents s3://nakom.is-static
aws s3 sync s3://nakom.is-static $SCRIPT_DIR/../s3contents
