#!/bin/bash

ACCESS_KEY_ID=$(aws ssm get-parameter --name "/nakom.is/nis/accessKeyId" --profile nakom.is-admin | jq .Parameter.Value | tr -d '"')
SECRET_ACCESS_KEY=$(aws ssm get-parameter --name "/nakom.is/nis/secretAccessKey" --profile nakom.is-admin | jq .Parameter.Value | tr -d '"')

security add-generic-password -a NIS -s NIS_ACCESS_KEY_ID -w $ACCESS_KEY_ID -U
security add-generic-password -a NIS -s NIS_SECRET_ACCESS_KEY -w $SECRET_ACCESS_KEY -U
