#!/bin/bash

SECRET_ACCESS_KEY=$(aws secretsmanager --profile nakom.is-admin get-secret-value --secret-id NISSecretAccessKey | jq '.SecretString' | tr -d '"')
ACCESS_KEY_ID=$(aws secretsmanager --profile nakom.is-admin get-secret-value --secret-id NISAccessKeyId | jq '.SecretString' | tr -d '"')

security add-generic-password -a NIS -s NIS_ACCESS_KEY_ID -w $ACCESS_KEY_ID -U
security add-generic-password -a NIS -s NIS_SECRET_ACCESS_KEY -w $SECRET_ACCESS_KEY -U
