#!/bin/bash

if [ -z "$1" ]; then
    echo 
    echo Usage: nis shortUrl
    echo
    exit 0
fi

. $(dirname "$0")/nis.env

export AWS_ACCESS_KEY_ID=$NIS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY="$NIS_SECRET_ACCESS_KEY"
export AWS_DEFAULT_REGION=eu-west-2
export AWS_REGION=eu-west-2
unset AWS_PROFILE
unset AWS_SESSION_TOKEN
unset AWS_SECURITY_TOKEN

aws dynamodb delete-item --table-name redirects --key '{"shortPath": {"S": "'$1'"}}' 
